### PR TITLE
Feature/49 dashboard

### PR DESCRIPTION
**Pull request by JavierRodriguezReina**
### **Description**
- Enhanced dashboard statistics functionality:
  * Added new methods for counting total dataset downloads and views
  * Refactored statistics collection to use repository methods
  * Added comprehensive unit tests

- Improved dataset seeding:
  * Increased number of seeded datasets to 10
  * Added realistic download and view records with random distribution
  * Added date distribution for more realistic test data
  
- Database schema updates:
  * Added comprehensive database schema with tables for communities, users, datasets
  * Added dataset rating functionality
  * Fixed migration corruption by merging database branches

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>repositories.py</strong><dd><code>Add dataset statistics counting methods</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

app/modules/dashboard/repositories.py

<li>Added new methods for counting total dataset downloads and views<br> <li> Removed unused auxiliary function<br>

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/123/files#diff-1860e81c653e101b4beb4dbd91420e11446515072f38976b48609b58b5d07927">+8/-3</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>services.py</strong><dd><code>Refactor statistics collection logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

app/modules/dashboard/services.py

<li>Refactored statistics collection to use new repository methods<br> <li> Removed unused repository imports<br>

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/123/files#diff-7800c4506d6f222ebbe142ce9899926eb38d8eb330c9f48c339d69e58757f545">+3/-6</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>seeders.py</strong><dd><code>Enhanced dataset seeder with views and downloads</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

app/modules/dataset/seeders.py

<li>Increased number of seeded datasets from 4 to 10<br> <li> Added random download and view records generation<br> <li> Added date distribution for realistic data<br>

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/123/files#diff-93ef01b1726825f88a43e0355aab3a07d9b6531151af646fbfa17b6c16318678">+50/-12</a>&nbsp; </td>

</tr>
</table></td></tr><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>test_unit.py</strong><dd><code>Update tests for new repository methods</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

app/modules/dashboard/tests/test_unit.py

<li>Updated test mocks to match new repository methods<br> <li> Added new tests for dataset downloads and views counting<br>

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/123/files#diff-4e9b464622d17dff6772cdce9334f309a11ff0bfae5d2f38af7b1c336cba2387">+12/-2</a>&nbsp; &nbsp; </td>

</tr>
</table></td></tr><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>6e881add63a5_two_heads_fusion.py</strong><dd><code>Database migration for branch merge</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

migrations/versions/6e881add63a5_two_heads_fusion.py

- Added migration for merging two database branches

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/123/files#diff-3213701b6f0f9a45f3eae78d3a96862245bf5c4b343e95a71b1781624fb3ac4c">+24/-0</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>70d0606c9360_.py</strong><dd><code>Initial database schema migration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

migrations/versions/70d0606c9360_.py

<li>Added comprehensive database schema migration<br> <li> Created tables for communities, users, datasets, and related entities<br>

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/123/files#diff-8a7da4f224449bc806c7e81ec3ae12e43b12f587c5700d8a84b0d839f9dd5e02">+238/-0</a>&nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>f343d206fef7_.py</strong><dd><code>Add dataset rating functionality</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

migrations/versions/f343d206fef7_.py

- Added dataset rating table and column

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/123/files#diff-7d2d011f5453a6a51084198baf987da6f2f6d270609b9c1c7103e0baad0e5302">+43/-0</a>&nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by rafduqcol** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 88.4600%
  **repositories.py**: 93.7500%
  **routes.py**: 53.6200%
  **services.py**: 63.00%

### **community**
  **forms.py**: 100%
  **models.py**: 97.300%
  **repositories.py**: 100%
  **routes.py**: 98.3200%
  **services.py**: 92.8600%

### **dashboard**
  **repositories.py**: 100%
  **routes.py**: 100%
  **services.py**: 100%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 77.600%
  **repositories.py**: 80.8800%
  **routes.py**: 29.3100%
  **services.py**: 37.500%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 19.5700%
  **routes.py**: 59.0900%
  **services.py**: 56.2500%

### **fakenodo**
  **forms.py**: 0%
  **models.py**: 87.500%
  **repositories.py**: 85.7100%
  **routes.py**: 41.1800%
  **services.py**: 36.8400%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 85.7100%
  **repositories.py**: 100%
  **routes.py**: 80.0%
  **services.py**: 80.0%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **github**
  **forms.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 83.3300%
  **services.py**: 94.500%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 25.00%
  **services.py**: 72.4100%

### **profile**
  **forms.py**: 100%
  **models.py**: 75.00%
  **repositories.py**: 100%
  **routes.py**: 63.6400%
  **services.py**: 60.0%

### **public**
  **routes.py**: 100%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.2400%

**Comment by rafduqcol** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 88.4600%
  **repositories.py**: 93.7500%
  **routes.py**: 53.6200%
  **services.py**: 63.00%

### **community**
  **forms.py**: 100%
  **models.py**: 97.300%
  **repositories.py**: 100%
  **routes.py**: 98.3200%
  **services.py**: 92.8600%

### **dashboard**
  **repositories.py**: 100%
  **routes.py**: 100%
  **services.py**: 100%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 77.600%
  **repositories.py**: 80.8800%
  **routes.py**: 29.3100%
  **services.py**: 37.500%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 19.5700%
  **routes.py**: 59.0900%
  **services.py**: 56.2500%

### **fakenodo**
  **forms.py**: 0%
  **models.py**: 87.500%
  **repositories.py**: 85.7100%
  **routes.py**: 41.1800%
  **services.py**: 36.8400%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 85.7100%
  **repositories.py**: 100%
  **routes.py**: 80.0%
  **services.py**: 80.0%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **github**
  **forms.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 83.3300%
  **services.py**: 94.500%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 25.00%
  **services.py**: 72.4100%

### **profile**
  **forms.py**: 100%
  **models.py**: 75.00%
  **repositories.py**: 100%
  **routes.py**: 63.6400%
  **services.py**: 60.0%

### **public**
  **routes.py**: 100%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.2400%

**Comment by rafduqcol** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 88.4600%
  **repositories.py**: 93.7500%
  **routes.py**: 53.6200%
  **services.py**: 63.00%

### **community**
  **forms.py**: 100%
  **models.py**: 97.300%
  **repositories.py**: 100%
  **routes.py**: 98.3200%
  **services.py**: 92.8600%

### **dashboard**
  **repositories.py**: 100%
  **routes.py**: 100%
  **services.py**: 100%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 77.600%
  **repositories.py**: 80.8800%
  **routes.py**: 29.3100%
  **services.py**: 37.500%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 19.5700%
  **routes.py**: 59.0900%
  **services.py**: 56.2500%

### **fakenodo**
  **forms.py**: 0%
  **models.py**: 87.500%
  **repositories.py**: 85.7100%
  **routes.py**: 41.1800%
  **services.py**: 36.8400%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 85.7100%
  **repositories.py**: 100%
  **routes.py**: 80.0%
  **services.py**: 80.0%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **github**
  **forms.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 83.3300%
  **services.py**: 94.500%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 25.00%
  **services.py**: 72.4100%

### **profile**
  **forms.py**: 100%
  **models.py**: 75.00%
  **repositories.py**: 100%
  **routes.py**: 63.6400%
  **services.py**: 60.0%

### **public**
  **routes.py**: 100%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.2400%

**Comment by rafduqcol** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 88.4600%
  **repositories.py**: 93.7500%
  **routes.py**: 53.6200%
  **services.py**: 63.00%

### **community**
  **forms.py**: 100%
  **models.py**: 97.300%
  **repositories.py**: 100%
  **routes.py**: 98.3200%
  **services.py**: 92.8600%

### **dashboard**
  **repositories.py**: 100%
  **routes.py**: 100%
  **services.py**: 100%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 77.600%
  **repositories.py**: 80.8800%
  **routes.py**: 29.3100%
  **services.py**: 37.500%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 19.5700%
  **routes.py**: 59.0900%
  **services.py**: 56.2500%

### **fakenodo**
  **forms.py**: 0%
  **models.py**: 87.500%
  **repositories.py**: 85.7100%
  **routes.py**: 41.1800%
  **services.py**: 36.8400%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 85.7100%
  **repositories.py**: 100%
  **routes.py**: 80.0%
  **services.py**: 80.0%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **github**
  **forms.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 83.3300%
  **services.py**: 94.500%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 25.00%
  **services.py**: 72.4100%

### **profile**
  **forms.py**: 100%
  **models.py**: 75.00%
  **repositories.py**: 100%
  **routes.py**: 63.6400%
  **services.py**: 60.0%

### **public**
  **routes.py**: 100%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.2400%

**Comment by rafduqcol** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 88.4600%
  **repositories.py**: 93.7500%
  **routes.py**: 53.6200%
  **services.py**: 63.00%

### **community**
  **forms.py**: 100%
  **models.py**: 97.300%
  **repositories.py**: 100%
  **routes.py**: 98.3200%
  **services.py**: 92.8600%

### **dashboard**
  **repositories.py**: 100%
  **routes.py**: 100%
  **services.py**: 100%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 77.600%
  **repositories.py**: 80.8800%
  **routes.py**: 29.3100%
  **services.py**: 37.500%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 19.5700%
  **routes.py**: 59.0900%
  **services.py**: 56.2500%

### **fakenodo**
  **forms.py**: 0%
  **models.py**: 87.500%
  **repositories.py**: 85.7100%
  **routes.py**: 41.1800%
  **services.py**: 36.8400%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 85.7100%
  **repositories.py**: 100%
  **routes.py**: 80.0%
  **services.py**: 80.0%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **github**
  **forms.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 83.3300%
  **services.py**: 94.500%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 25.00%
  **services.py**: 72.4100%

### **profile**
  **forms.py**: 100%
  **models.py**: 75.00%
  **repositories.py**: 100%
  **routes.py**: 63.6400%
  **services.py**: 60.0%

### **public**
  **routes.py**: 100%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.2400%

**Review by hugborang — APPROVED** [review]
Buen trabajo

**Pull request merged**
