### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by rafduqcol**
### **Description**
- Added new routes and services for exploring and filtering models, including a new `ModelService` class.
- Implemented integration, unit, and Selenium tests for model exploration and export functionalities.
- Translated comments and user-facing text from Spanish to English for better accessibility.
- Added migration scripts for database schema updates and merging heads.
- Configured static folder for the explore blueprint and updated ChromeDriver initialization path.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>8 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>routes.py</strong><dd><code>Improve readability and translate comments to English</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

app/modules/auth/routes.py

<li>Added new lines for better readability.<br> <li> Translated comments and flash messages from Spanish to English.<br>

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/106/files#diff-963a535e3314b06ed9ddd3ae208d1834ccb74cece0a845c0d12997210391bf24">+15/-13</a>&nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>services.py</strong><dd><code>Translate service docstrings to English</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

app/modules/auth/services.py

- Translated docstrings and comments from Spanish to English.

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/106/files#diff-7912b0af5f27407c50cd8ae0f3641f3c002509a1f699ab611d09a517311a499d">+12/-12</a>&nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>forms.py</strong><dd><code>Add ModelForm class</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

app/modules/explore/forms.py

- Added a new form class `ModelForm`.

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/106/files#diff-1ef8608a4556c3d20d0f8691398a49e3b88cb93cfa08a5f8e10eb30498773412">+4/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>routes.py</strong><dd><code>Add route for exploring models with filtering</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

app/modules/explore/routes.py

<li>Added a new route for exploring models.<br> <li> Integrated <code>ModelForm</code> and <code>ModelService</code> for model filtering.<br>

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/106/files#diff-a15518baf8cd8dd50b4a6fc58ff5cfb98318134587cf727b560f836d9c740e21">+13/-3</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>services.py</strong><dd><code>Implement ModelService for model operations</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

app/modules/explore/services.py

<li>Added <code>ModelService</code> class with methods for retrieving and filtering <br>models.<br>

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/106/files#diff-cb645156571b3cfacdc5a751ead2dc2c4ab6056a43387f5aa1312d375cf3cfec">+13/-1</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>models.py</strong><dd><code>Add to_dict methods for model serialization</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

app/modules/featuremodel/models.py

- Added `to_dict` methods for `FeatureModel` and `FMMetaData`.

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/106/files#diff-65414dc6232cb579368bbe5e570c72c24eb5cc12093bba7106614d7a0cc478fc">+19/-0</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>login_form.html</strong><dd><code>Translate password recovery link text</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

app/modules/auth/templates/auth/login_form.html

- Translated password recovery link text to English.

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/106/files#diff-435ea331e1c9f93b0374829ba403a41679768d98c39371a611f66b507f73a62e">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>index.html</strong><dd><code>Create explore models template with search functionality</code>&nbsp; </dd></summary>
<hr>

app/modules/explore/templates/explore2/index.html

<li>Created a new template for exploring models.<br> <li> Added search functionality and display logic for models.<br>

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/106/files#diff-cf5e07a93cdc4485b969274bad56dfd8fb0a90213b438ed8457707a542913e94">+104/-0</a>&nbsp; </td>

</tr>
</table></details></td></tr><tr><td><strong>Tests</strong></td><td><details><summary>4 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>test_integracion.py</strong><dd><code>Add integration tests for dataset export</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

app/modules/dataset/tests/test_integracion.py

<li>Added integration tests for dataset export functionality.<br> <li> Implemented tests for various export formats and error handling.<br>

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/106/files#diff-7002b95f5c83791ece4f46c36789fc91a24c639a671e1f5583deee73c99198be">+85/-0</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>locustfile.py</strong><dd><code>Add Locust performance tests for model exploration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

app/modules/explore/tests/locustfile.py

- Added Locust performance tests for exploring models.

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/106/files#diff-10e7b1301037a642a9b048ee277e8430ced5483078cabe6802067ac4def9d15c">+27/-0</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>test_explore_unit.py</strong><dd><code>Add unit tests for model search functionality</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

app/modules/explore/tests/test_explore_unit.py

<li>Added unit tests for model search functionality.<br> <li> Tested various search scenarios including partial matches and case <br>insensitivity.<br>

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/106/files#diff-1717d892e8c7a0dae3bc1eb4af68d0cda8a45689351d08c4034d967716b2b70d">+148/-0</a>&nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>test_selenium.py</strong><dd><code>Implement Selenium tests for explore models page</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

app/modules/explore/tests/test_selenium.py

<li>Implemented Selenium tests for the explore models page.<br> <li> Verified navigation and element visibility.<br>

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/106/files#diff-313e5cc570083292ed71662a27b63a94573c5480341f230a6f8787b78724a9e1">+77/-0</a>&nbsp; &nbsp; </td>

</tr>
</table></details></td></tr><tr><td><strong>Configuration changes</strong></td><td><details><summary>2 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>__init__.py</strong><dd><code>Configure static folder for explore blueprint</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

app/modules/explore/__init__.py

- Added static folder configuration to the explore blueprint.

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/106/files#diff-ba41fcb3aa48e5c9922e1e1a738b6c603e6a1577e720240e4d101ab1a1d51a35">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>common.py</strong><dd><code>Update ChromeDriver initialization path</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

core/selenium/common.py

<li>Adjusted driver initialization to use a specific path for <br>ChromeDriver.<br>

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/106/files#diff-dacbda3972d06b857c123896e0dc67336b1f62ffc1625d64c4793c903557efdb">+4/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></details></td></tr><tr><td><strong>Dependencies</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>4793b2b584aa_merge_heads.py</strong><dd><code>Add migration script for merging heads</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

migrations/versions/4793b2b584aa_merge_heads.py

- Added migration script for merging database heads.

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/106/files#diff-ba25b5000a104ecc23dda1e3fa722128ed8f79cd4145fbb24e4f4ce40cc27613">+24/-0</a>&nbsp; &nbsp; </td>

</tr>
</table></details></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Review by hugborang — APPROVED** [review]

**Review by fracalrod3 — APPROVED** [review]
Nicely done, now u just need to resolve conflicts

**Comment by rafduqcol** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 88.4600%
  **repositories.py**: 88.8900%
  **routes.py**: 52.00%
  **services.py**: 61.5400%

### **community**
  **forms.py**: 100%
  **models.py**: 97.300%
  **repositories.py**: 100%
  **routes.py**: 98.3200%
  **services.py**: 92.8600%

### **dashboard**
  **repositories.py**: 100%
  **routes.py**: 100%
  **services.py**: 100%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 77.600%
  **repositories.py**: 82.3500%
  **routes.py**: 29.3100%
  **services.py**: 37.500%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 76.0900%
  **routes.py**: 81.8200%
  **services.py**: 68.7500%

### **fakenodo**
  **forms.py**: 0%
  **models.py**: 87.500%
  **repositories.py**: 85.7100%
  **routes.py**: 41.1800%
  **services.py**: 36.8400%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 85.7100%
  **repositories.py**: 100%
  **routes.py**: 80.0%
  **services.py**: 80.0%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **github**
  **forms.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 83.3300%
  **services.py**: 94.500%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 25.00%
  **services.py**: 72.4100%

### **profile**
  **forms.py**: 100%
  **models.py**: 75.00%
  **repositories.py**: 100%
  **routes.py**: 63.6400%
  **services.py**: 60.0%

### **public**
  **routes.py**: 100%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.2400%

**Comment by rafduqcol** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 88.4600%
  **repositories.py**: 88.8900%
  **routes.py**: 52.00%
  **services.py**: 61.5400%

### **community**
  **forms.py**: 100%
  **models.py**: 97.300%
  **repositories.py**: 100%
  **routes.py**: 98.3200%
  **services.py**: 92.8600%

### **dashboard**
  **repositories.py**: 100%
  **routes.py**: 100%
  **services.py**: 100%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 77.600%
  **repositories.py**: 82.3500%
  **routes.py**: 29.3100%
  **services.py**: 37.500%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 76.0900%
  **routes.py**: 81.8200%
  **services.py**: 68.7500%

### **fakenodo**
  **forms.py**: 0%
  **models.py**: 87.500%
  **repositories.py**: 85.7100%
  **routes.py**: 41.1800%
  **services.py**: 36.8400%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 85.7100%
  **repositories.py**: 100%
  **routes.py**: 80.0%
  **services.py**: 80.0%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **github**
  **forms.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 83.3300%
  **services.py**: 94.500%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 25.00%
  **services.py**: 72.4100%

### **profile**
  **forms.py**: 100%
  **models.py**: 75.00%
  **repositories.py**: 100%
  **routes.py**: 63.6400%
  **services.py**: 60.0%

### **public**
  **routes.py**: 100%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.2400%

**Comment by rafduqcol** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 88.4600%
  **repositories.py**: 88.8900%
  **routes.py**: 52.00%
  **services.py**: 61.5400%

### **community**
  **forms.py**: 100%
  **models.py**: 97.300%
  **repositories.py**: 100%
  **routes.py**: 98.3200%
  **services.py**: 92.8600%

### **dashboard**
  **repositories.py**: 100%
  **routes.py**: 100%
  **services.py**: 100%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 77.600%
  **repositories.py**: 82.3500%
  **routes.py**: 29.3100%
  **services.py**: 37.500%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 76.0900%
  **routes.py**: 81.8200%
  **services.py**: 68.7500%

### **fakenodo**
  **forms.py**: 0%
  **models.py**: 87.500%
  **repositories.py**: 85.7100%
  **routes.py**: 41.1800%
  **services.py**: 36.8400%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 85.7100%
  **repositories.py**: 100%
  **routes.py**: 80.0%
  **services.py**: 80.0%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **github**
  **forms.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 83.3300%
  **services.py**: 94.500%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 25.00%
  **services.py**: 72.4100%

### **profile**
  **forms.py**: 100%
  **models.py**: 75.00%
  **repositories.py**: 100%
  **routes.py**: 63.6400%
  **services.py**: 60.0%

### **public**
  **routes.py**: 100%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.2400%

**Comment by rafduqcol** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 88.4600%
  **repositories.py**: 88.8900%
  **routes.py**: 52.00%
  **services.py**: 61.5400%

### **community**
  **forms.py**: 100%
  **models.py**: 97.300%
  **repositories.py**: 100%
  **routes.py**: 98.3200%
  **services.py**: 92.8600%

### **dashboard**
  **repositories.py**: 100%
  **routes.py**: 100%
  **services.py**: 100%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 77.600%
  **repositories.py**: 82.3500%
  **routes.py**: 29.3100%
  **services.py**: 37.500%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 76.0900%
  **routes.py**: 81.8200%
  **services.py**: 68.7500%

### **fakenodo**
  **forms.py**: 0%
  **models.py**: 87.500%
  **repositories.py**: 85.7100%
  **routes.py**: 41.1800%
  **services.py**: 36.8400%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 85.7100%
  **repositories.py**: 100%
  **routes.py**: 80.0%
  **services.py**: 80.0%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **github**
  **forms.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 83.3300%
  **services.py**: 94.500%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 25.00%
  **services.py**: 72.4100%

### **profile**
  **forms.py**: 100%
  **models.py**: 75.00%
  **repositories.py**: 100%
  **routes.py**: 63.6400%
  **services.py**: 60.0%

### **public**
  **routes.py**: 100%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.2400%

**Pull request merged**
