### PR TITLE
Feature/78 advanced filtering tests

### PR DESCRIPTION
**Pull request by mohamedabouri**
### **User description**
All tests are done!

___

### **Description**
- Added comprehensive test suite for advanced filtering functionality:
  - Unit tests for filter combinations and edge cases
  - Integration tests for filter functionality
  - Load tests using Locust
  - Selenium tests for UI interactions
- Enhanced user management features:
  - Added user listing functionality
  - Implemented repository and service methods for user management
  - Created user list view template
- Improved dataset filtering:
  - Changed metrics fields to Integer type
  - Added null checks and better type handling
  - Updated seeders for consistent data types
- Updated documentation with detailed setup instructions

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>7 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>models.py</strong><dd><code>Add UserProfile model import</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

app/modules/auth/models.py

- Added import of UserProfile model from profile module

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/112/files#diff-5f34c977db145d343543e35fca7b44783597c3ef7a4e5210843b86bf14aee657">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>repositories.py</strong><dd><code>Add get_all users repository method</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

app/modules/auth/repositories.py

- Added get_all method to retrieve all users

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/112/files#diff-378a07ede4298cac6523544fec1c994fbe68ccb704a15ad835acdaf149cf30d3">+3/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>routes.py</strong><dd><code>Add user listing route and clean up code</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

app/modules/auth/routes.py

<li>Added new route '/listarUsuarios' to list all users<br> <li> Fixed typos in password recovery comments<br> <li> Removed debug print statements<br>

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/112/files#diff-963a535e3314b06ed9ddd3ae208d1834ccb74cece0a845c0d12997210391bf24">+14/-9</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>services.py</strong><dd><code>Add list users service and clean up code</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

app/modules/auth/services.py

<li>Added list_users method to get all users<br> <li> Fixed Spanish characters in comments<br> <li> Removed unnecessary comments<br>

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/112/files#diff-7912b0af5f27407c50cd8ae0f3641f3c002509a1f699ab611d09a517311a499d">+11/-8</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>models.py</strong><dd><code>Update dataset metrics field types</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

app/modules/dataset/models.py

<li>Changed number_of_features and number_of_products fields to Integer <br>type<br>

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/112/files#diff-49cd90d62577c0ffae669f6704967238492cfa396cb9a22d28d4b057d09bced1">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>seeders.py</strong><dd><code>Update dataset metrics seeder</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

app/modules/dataset/seeders.py

- Updated DSMetrics seeder to use integer values

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/112/files#diff-93ef01b1726825f88a43e0355aab3a07d9b6531151af646fbfa17b6c16318678">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>repositories.py</strong><dd><code>Enhance dataset filtering functionality</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

app/modules/explore/repositories.py

<li>Added null checks for number_of_features and number_of_products<br> <li> Updated filter to handle integer comparisons<br>

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/112/files#diff-8978d8e3fe7340c64583c5e31168939913638571b64293e260d114f7fc951341">+4/-4</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></details></td></tr><tr><td><strong>Tests</strong></td><td><details><summary>7 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>prueba_carga.py</strong><dd><code>Add load testing for user listing feature</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

app/modules/auth/tests/prueba_carga.py

<li>Added load test for user listing functionality<br> <li> Implements login, page access, and logout tests<br>

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/112/files#diff-77443e2490120979f8baafb70739c9e6858a7aa317ca47c0bbed1f6ed9900f28">+36/-0</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>test_cargarAcceso.py</strong><dd><code>Add Selenium tests for dataset access</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

app/modules/auth/tests/test_selenium_ide/test_cargarAcceso.py

<li>Added Selenium test for dataset access functionality<br> <li> Tests navigation and login process<br>

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/112/files#diff-4464aa93fb4e7a959161c3489bb185b3c306d38f45e2f4b29753b4a2436dd6a4">+30/-0</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>test_cargarListado.py</strong><dd><code>Add Selenium tests for user listing</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

app/modules/auth/tests/test_selenium_ide/test_cargarListado.py

<li>Added Selenium test for user listing functionality<br> <li> Tests navigation, login, and user list access<br>

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/112/files#diff-4b6ad892100a9eec6cccdb4120a5675da910a003368cb32f2202783e8fe1ecd3">+35/-0</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>test_unit.py</strong><dd><code>Add and update user management unit tests</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

app/modules/auth/tests/test_unit.py

<li>Added unit tests for user creation and profile handling<br> <li> Fixed test data formatting<br>

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/112/files#diff-8962a795efc9c990b985f29e4dc0ea3642312b841956bd7b782e426a88c29386">+165/-3</a>&nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>locustfile.py</strong><dd><code>Add load testing for filtering features</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

app/modules/explore/tests/locustfile.py

<li>Added load testing for filtering functionality<br> <li> Implements various filter combination tests<br>

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/112/files#diff-10e7b1301037a642a9b048ee277e8430ced5483078cabe6802067ac4def9d15c">+88/-0</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>test_integration.py</strong><dd><code>Add filtering integration tests</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

app/modules/explore/tests/test_integration.py

<li>Added integration tests for filtering functionality<br> <li> Tests various filter combinations and edge cases<br>

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/112/files#diff-f8c0b5c5efb95d30b2c75f1c0c760bd996f05bc8c1d061b0a9eaf435c8b2d2fb">+126/-0</a>&nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>test_unit.py</strong><dd><code>Add filtering unit tests</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

app/modules/explore/tests/test_unit.py

<li>Added comprehensive unit tests for filtering service<br> <li> Tests all filter combinations and edge cases<br>

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/112/files#diff-830398e98aed47999120b519fd9604c1627dbda0cc0d1d5b31b2adf8c8b62560">+379/-0</a>&nbsp; </td>

</tr>
</table></details></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by rafduqcol** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 88.4600%
  **repositories.py**: 88.8900%
  **routes.py**: 51.3200%
  **services.py**: 61.5400%

### **community**
  **forms.py**: 100%
  **models.py**: 97.300%
  **repositories.py**: 100%
  **routes.py**: 98.3200%
  **services.py**: 92.8600%

### **dashboard**
  **repositories.py**: 98.700%
  **routes.py**: 100%
  **services.py**: 100%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 77.600%
  **repositories.py**: 82.3500%
  **routes.py**: 29.3100%
  **services.py**: 37.500%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 76.0900%
  **routes.py**: 81.8200%
  **services.py**: 68.7500%

### **fakenodo**
  **forms.py**: 0%
  **models.py**: 87.500%
  **repositories.py**: 85.7100%
  **routes.py**: 41.1800%
  **services.py**: 36.8400%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 85.7100%
  **repositories.py**: 100%
  **routes.py**: 80.0%
  **services.py**: 80.0%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **github**
  **forms.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 83.3300%
  **services.py**: 94.500%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 25.00%
  **services.py**: 72.4100%

### **profile**
  **forms.py**: 100%
  **models.py**: 75.00%
  **repositories.py**: 100%
  **routes.py**: 63.6400%
  **services.py**: 60.0%

### **public**
  **routes.py**: 100%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.2400%

**Comment by rafduqcol** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 88.4600%
  **repositories.py**: 88.8900%
  **routes.py**: 51.3200%
  **services.py**: 61.5400%

### **community**
  **forms.py**: 100%
  **models.py**: 97.300%
  **repositories.py**: 100%
  **routes.py**: 98.3200%
  **services.py**: 92.8600%

### **dashboard**
  **repositories.py**: 98.700%
  **routes.py**: 100%
  **services.py**: 100%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 77.600%
  **repositories.py**: 82.3500%
  **routes.py**: 29.3100%
  **services.py**: 37.500%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 76.0900%
  **routes.py**: 81.8200%
  **services.py**: 68.7500%

### **fakenodo**
  **forms.py**: 0%
  **models.py**: 87.500%
  **repositories.py**: 85.7100%
  **routes.py**: 41.1800%
  **services.py**: 36.8400%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 85.7100%
  **repositories.py**: 100%
  **routes.py**: 80.0%
  **services.py**: 80.0%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **github**
  **forms.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 83.3300%
  **services.py**: 94.500%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 25.00%
  **services.py**: 72.4100%

### **profile**
  **forms.py**: 100%
  **models.py**: 75.00%
  **repositories.py**: 100%
  **routes.py**: 63.6400%
  **services.py**: 60.0%

### **public**
  **routes.py**: 100%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.2400%

**Comment by rafduqcol** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 88.4600%
  **repositories.py**: 88.8900%
  **routes.py**: 51.3200%
  **services.py**: 61.5400%

### **community**
  **forms.py**: 100%
  **models.py**: 97.300%
  **repositories.py**: 100%
  **routes.py**: 98.3200%
  **services.py**: 92.8600%

### **dashboard**
  **repositories.py**: 98.700%
  **routes.py**: 100%
  **services.py**: 100%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 77.600%
  **repositories.py**: 82.3500%
  **routes.py**: 29.3100%
  **services.py**: 37.500%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 76.0900%
  **routes.py**: 81.8200%
  **services.py**: 68.7500%

### **fakenodo**
  **forms.py**: 0%
  **models.py**: 87.500%
  **repositories.py**: 85.7100%
  **routes.py**: 41.1800%
  **services.py**: 36.8400%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 85.7100%
  **repositories.py**: 100%
  **routes.py**: 80.0%
  **services.py**: 80.0%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **github**
  **forms.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 83.3300%
  **services.py**: 94.500%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 25.00%
  **services.py**: 72.4100%

### **profile**
  **forms.py**: 100%
  **models.py**: 75.00%
  **repositories.py**: 100%
  **routes.py**: 63.6400%
  **services.py**: 60.0%

### **public**
  **routes.py**: 100%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.2400%

**Comment by rafduqcol** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 88.4600%
  **repositories.py**: 88.8900%
  **routes.py**: 51.3200%
  **services.py**: 61.5400%

### **community**
  **forms.py**: 100%
  **models.py**: 97.300%
  **repositories.py**: 100%
  **routes.py**: 98.3200%
  **services.py**: 92.8600%

### **dashboard**
  **repositories.py**: 98.700%
  **routes.py**: 100%
  **services.py**: 100%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 77.600%
  **repositories.py**: 82.3500%
  **routes.py**: 29.3100%
  **services.py**: 37.500%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 76.0900%
  **routes.py**: 81.8200%
  **services.py**: 68.7500%

### **fakenodo**
  **forms.py**: 0%
  **models.py**: 87.500%
  **repositories.py**: 85.7100%
  **routes.py**: 41.1800%
  **services.py**: 36.8400%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 85.7100%
  **repositories.py**: 100%
  **routes.py**: 80.0%
  **services.py**: 80.0%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **github**
  **forms.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 83.3300%
  **services.py**: 94.500%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 25.00%
  **services.py**: 72.4100%

### **profile**
  **forms.py**: 100%
  **models.py**: 75.00%
  **repositories.py**: 100%
  **routes.py**: 63.6400%
  **services.py**: 60.0%

### **public**
  **routes.py**: 100%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.2400%

**Review by fracalrod3 — APPROVED** [review]
Everything working no problem, good job!

**Comment by rafduqcol** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 88.4600%
  **repositories.py**: 88.8900%
  **routes.py**: 52.00%
  **services.py**: 61.5400%

### **community**
  **forms.py**: 100%
  **models.py**: 97.300%
  **repositories.py**: 100%
  **routes.py**: 98.3200%
  **services.py**: 92.8600%

### **dashboard**
  **repositories.py**: 100%
  **routes.py**: 100%
  **services.py**: 100%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 77.600%
  **repositories.py**: 82.3500%
  **routes.py**: 29.3100%
  **services.py**: 37.500%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 76.0900%
  **routes.py**: 81.8200%
  **services.py**: 68.7500%

### **fakenodo**
  **forms.py**: 0%
  **models.py**: 87.500%
  **repositories.py**: 85.7100%
  **routes.py**: 41.1800%
  **services.py**: 36.8400%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 85.7100%
  **repositories.py**: 100%
  **routes.py**: 80.0%
  **services.py**: 80.0%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **github**
  **forms.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 83.3300%
  **services.py**: 94.500%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 25.00%
  **services.py**: 72.4100%

### **profile**
  **forms.py**: 100%
  **models.py**: 75.00%
  **repositories.py**: 100%
  **routes.py**: 63.6400%
  **services.py**: 60.0%

### **public**
  **routes.py**: 100%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.2400%

**Comment by rafduqcol** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 88.4600%
  **repositories.py**: 88.8900%
  **routes.py**: 52.00%
  **services.py**: 61.5400%

### **community**
  **forms.py**: 100%
  **models.py**: 97.300%
  **repositories.py**: 100%
  **routes.py**: 98.3200%
  **services.py**: 92.8600%

### **dashboard**
  **repositories.py**: 100%
  **routes.py**: 100%
  **services.py**: 100%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 77.600%
  **repositories.py**: 82.3500%
  **routes.py**: 29.3100%
  **services.py**: 37.500%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 76.0900%
  **routes.py**: 81.8200%
  **services.py**: 68.7500%

### **fakenodo**
  **forms.py**: 0%
  **models.py**: 87.500%
  **repositories.py**: 85.7100%
  **routes.py**: 41.1800%
  **services.py**: 36.8400%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 85.7100%
  **repositories.py**: 100%
  **routes.py**: 80.0%
  **services.py**: 80.0%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **github**
  **forms.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 83.3300%
  **services.py**: 94.500%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 25.00%
  **services.py**: 72.4100%

### **profile**
  **forms.py**: 100%
  **models.py**: 75.00%
  **repositories.py**: 100%
  **routes.py**: 63.6400%
  **services.py**: 60.0%

### **public**
  **routes.py**: 100%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.2400%

**Review by rafduqcol — APPROVED** [review]

**Pull request merged**
