### PR TITLE
feat: Added Coverage to test's workflow

### PR DESCRIPTION
**Pull request by ivaramlar**
### **User description**
Added coverage functionality to the test's workflow

___

### **Description**
- Added comprehensive test coverage reporting to the CI pipeline:
  - Tests now generate XML coverage reports using pytest-cov
  - Coverage data is parsed and formatted for readability
  - Automated PR comments showing coverage percentages for each module
- Enhanced workflow configuration:
  - Added 'build' branch to PR triggers
  - Added specific PR event types (opened, synchronize, reopened)
- Improved error handling for GitHub token availability
- Excluded specific files (locustfile.py, seeders.py) from coverage reporting

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>tests.yml</strong><dd><code>Add test coverage reporting and PR feedback</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

.github/workflows/tests.yml

<li>Added test coverage reporting functionality with XML output<br> <li> Added parsing and formatting of coverage data for PR comments<br> <li> Added GitHub workflow steps to comment coverage results on PRs<br> <li> Updated workflow triggers to include 'build' branch and specific PR <br>events<br>

</details>

  </td>
  <td><a href="https://github.com/EGC-Gazpacho/gazpacho-hub/pull/120/files#diff-1db27d93186e46d3b441ece35801b244db8ee144ff1405ca27a163bfe878957f">+104/-37</a></td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by rafduqcol** [comment]
## Test Coverage Report
**.**,__init__.py_1,conftest.py_1,**auth**,__init__.py_1,forms.py_1,models.py_0.8846,repositories.py_0.9375,routes.py_0.5362,seeders.py_0,services.py_0.63,**auth.tests**,__init__.py_1,locustfile.py_0,test_selenium.py_0,test_unit.py_1,**auth.tests.tests_remember_my_password**,__init__.py_1,locustfile.py_0,test_selenium.py_0,test_unit.py_1,**community**,__init__.py_1,forms.py_1,models.py_0.973,repositories.py_1,routes.py_0.9832,seeders.py_0,services.py_0.9286,**community.tests**,__init__.py_1,locustfile.py_0,test_integration.py_1,test_selenium.py_0,test_unit.py_0.9931,**dashboard**,__init__.py_1,repositories.py_0.987,routes.py_1,services.py_1,**dashboard.tests**,test_unit.py_1,**dataset**,__init__.py_1,api.py_1,forms.py_0.78,models.py_0.776,repositories.py_0.75,routes.py_0.1884,seeders.py_0,services.py_0.3561,**dataset.tests**,__init__.py_1,locustfile.py_0,prueba_carga.py_0,test_downloadindifferentformatsselenium.py_0,test_integracion.py_0.913,test_selenium.py_0,test_unit.py_1,**explore**,__init__.py_1,forms.py_1,repositories.py_0.1957,routes.py_0.5909,services.py_0.5625,**explore.tests**,test_explore_unit.py_1,**fakenodo**,__init__.py_1,forms.py_0,models.py_0.875,repositories.py_0.8571,routes.py_0.4118,seeders.py_0,services.py_0.3684,**fakenodo.tests**,__init__.py_1,locustfile.py_0,test_selenium.py_0,test_unit.py_1,**featuremodel**,__init__.py_1,forms.py_0,models.py_0.8571,repositories.py_1,routes.py_0.8,seeders.py_0,services.py_0.8,**featuremodel.tests**,__init__.py_1,locustfile.py_0,test_selenium.py_0,test_unit.py_1,**flamapy**,__init__.py_1,forms.py_0,models.py_1,repositories.py_0,routes.py_0.3194,seeders.py_0,services.py_0,**flamapy.tests**,__init__.py_1,locustfile.py_0,test_selenium.py_0,test_unit.py_1,**github**,__init__.py_1,forms.py_1,repositories.py_1,routes.py_0.8333,services.py_0.945,**github.tests**,__init__.py_1,locustfile.py_0,test_integration.py_1,test_selenium.py_0,test_unit.py_1,**hubfile**,__init__.py_1,forms.py_0,models.py_0.7391,repositories.py_0.9231,routes.py_0.25,seeders.py_0,services.py_0.7241,**hubfile.tests**,__init__.py_1,locustfile.py_0,test_selenium.py_0,test_unit.py_1,**profile**,__init__.py_1,forms.py_1,models.py_0.75,repositories.py_1,routes.py_0.6364,services.py_0.6,**profile.tests**,__init__.py_1,test_unit.py_1,**public**,__init__.py_1,routes.py_1,**team**,__init__.py_1,routes.py_0.8,**webhook**,__init__.py_1,forms.py_0,models.py_0,repositories.py_0,routes.py_0,seeders.py_0,services.py_0,**webhook.tests**,__init__.py_1,test_selenium.py_0,test_unit.py_1,**zenodo**,__init__.py_1,forms.py_0,models.py_1,repositories.py_1,routes.py_0.7,services.py_0.3524

**Comment by rafduqcol** [comment]
## Test Coverage Report
## .\n__init__.py: 100.00%\nconftest.py: 100.00%\n## auth\n__init__.py: 100.00%\nforms.py: 100.00%\nmodels.py: 88.46%\nrepositories.py: 93.75%\nroutes.py: 53.62%\nseeders.py: 0.00%\nservices.py: 63.00%\n## auth.tests\n__init__.py: 100.00%\nlocustfile.py: 0.00%\ntest_selenium.py: 0.00%\ntest_unit.py: 100.00%\n## auth.tests.tests_remember_my_password\n__init__.py: 100.00%\nlocustfile.py: 0.00%\ntest_selenium.py: 0.00%\ntest_unit.py: 100.00%\n## community\n__init__.py: 100.00%\nforms.py: 100.00%\nmodels.py: 97.30%\nrepositories.py: 100.00%\nroutes.py: 98.32%\nseeders.py: 0.00%\nservices.py: 92.86%\n## community.tests\n__init__.py: 100.00%\nlocustfile.py: 0.00%\ntest_integration.py: 100.00%\ntest_selenium.py: 0.00%\ntest_unit.py: 99.31%\n## dashboard\n__init__.py: 100.00%\nrepositories.py: 98.70%\nroutes.py: 100.00%\nservices.py: 100.00%\n## dashboard.tests\ntest_unit.py: 100.00%\n## dataset\n__init__.py: 100.00%\napi.py: 100.00%\nforms.py: 78.00%\nmodels.py: 77.60%\nrepositories.py: 75.00%\nroutes.py: 18.84%\nseeders.py: 0.00%\nservices.py: 35.61%\n## dataset.tests\n__init__.py: 100.00%\nlocustfile.py: 0.00%\nprueba_carga.py: 0.00%\ntest_downloadindifferentformatsselenium.py: 0.00%\ntest_integracion.py: 91.30%\ntest_selenium.py: 0.00%\ntest_unit.py: 100.00%\n## explore\n__init__.py: 100.00%\nforms.py: 100.00%\nrepositories.py: 19.57%\nroutes.py: 59.09%\nservices.py: 56.25%\n## explore.tests\ntest_explore_unit.py: 100.00%\n## fakenodo\n__init__.py: 100.00%\nforms.py: 0.00%\nmodels.py: 87.50%\nrepositories.py: 85.71%\nroutes.py: 41.18%\nseeders.py: 0.00%\nservices.py: 36.84%\n## fakenodo.tests\n__init__.py: 100.00%\nlocustfile.py: 0.00%\ntest_selenium.py: 0.00%\ntest_unit.py: 100.00%\n## featuremodel\n__init__.py: 100.00%\nforms.py: 0.00%\nmodels.py: 85.71%\nrepositories.py: 100.00%\nroutes.py: 80.00%\nseeders.py: 0.00%\nservices.py: 80.00%\n## featuremodel.tests\n__init__.py: 100.00%\nlocustfile.py: 0.00%\ntest_selenium.py: 0.00%\ntest_unit.py: 100.00%\n## flamapy\n__init__.py: 100.00%\nforms.py: 0.00%\nmodels.py: 100.00%\nrepositories.py: 0.00%\nroutes.py: 31.94%\nseeders.py: 0.00%\nservices.py: 0.00%\n## flamapy.tests\n__init__.py: 100.00%\nlocustfile.py: 0.00%\ntest_selenium.py: 0.00%\ntest_unit.py: 100.00%\n## github\n__init__.py: 100.00%\nforms.py: 100.00%\nrepositories.py: 100.00%\nroutes.py: 83.33%\nservices.py: 94.50%\n## github.tests\n__init__.py: 100.00%\nlocustfile.py: 0.00%\ntest_integration.py: 100.00%\ntest_selenium.py: 0.00%\ntest_unit.py: 100.00%\n## hubfile\n__init__.py: 100.00%\nforms.py: 0.00%\nmodels.py: 73.91%\nrepositories.py: 92.31%\nroutes.py: 25.00%\nseeders.py: 0.00%\nservices.py: 72.41%\n## hubfile.tests\n__init__.py: 100.00%\nlocustfile.py: 0.00%\ntest_selenium.py: 0.00%\ntest_unit.py: 100.00%\n## profile\n__init__.py: 100.00%\nforms.py: 100.00%\nmodels.py: 75.00%\nrepositories.py: 100.00%\nroutes.py: 63.64%\nservices.py: 60.00%\n## profile.tests\n__init__.py: 100.00%\ntest_unit.py: 100.00%\n## public\n__init__.py: 100.00%\nroutes.py: 100.00%\n## team\n__init__.py: 100.00%\nroutes.py: 80.00%\n## webhook\n__init__.py: 100.00%\nforms.py: 0.00%\nmodels.py: 0.00%\nrepositories.py: 0.00%\nroutes.py: 0.00%\nseeders.py: 0.00%\nservices.py: 0.00%\n## webhook.tests\n__init__.py: 100.00%\ntest_selenium.py: 0.00%\ntest_unit.py: 100.00%\n## zenodo\n__init__.py: 100.00%\nforms.py: 0.00%\nmodels.py: 100.00%\nrepositories.py: 100.00%\nroutes.py: 70.00%\nservices.py: 35.24%

**Comment by rafduqcol** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 88.4600%
  **repositories.py**: 93.7500%
  **routes.py**: 53.6200%
  **services.py**: 63.00%

### **community**
  **forms.py**: 100%
  **models.py**: 97.300%
  **repositories.py**: 100%
  **routes.py**: 98.3200%
  **services.py**: 92.8600%

### **dashboard**
  **repositories.py**: 98.700%
  **routes.py**: 100%
  **services.py**: 100%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 77.600%
  **repositories.py**: 75.00%
  **routes.py**: 18.8400%
  **services.py**: 35.6100%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 19.5700%
  **routes.py**: 59.0900%
  **services.py**: 56.2500%

### **fakenodo**
  **forms.py**: 0%
  **models.py**: 87.500%
  **repositories.py**: 85.7100%
  **routes.py**: 41.1800%
  **services.py**: 36.8400%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 85.7100%
  **repositories.py**: 100%
  **routes.py**: 80.0%
  **services.py**: 80.0%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **github**
  **forms.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 83.3300%
  **services.py**: 94.500%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 25.00%
  **services.py**: 72.4100%

### **profile**
  **forms.py**: 100%
  **models.py**: 75.00%
  **repositories.py**: 100%
  **routes.py**: 63.6400%
  **services.py**: 60.0%

### **public**
  **routes.py**: 100%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.2400%

**Review by fracalrod3 — APPROVED** [review]
Shows tests coverage as intended

**Pull request merged**
